services:
  commafeed:
    image: athou/commafeed:latest-postgresql
    container_name: commafeed
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - private
      - anarchy-pizza

  commafeed-postgresql:
    image: postgres:latest
    container_name: commafeed-postgresql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /storage/appdata/silver/commafeed-postgresql:/var/lib/postgresql
    networks:
      - private

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza
  private:
    driver: bridge
